version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app/static/uploads:/app/app/static/uploads
      - ./data:/app/data
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
    restart: unless-stopped 